### ISSUE TITLE
Make AnimateTransition available on npm

### ISSUE THREAD

**Issue by maximilianschmitt** [Rapid-Application-Development-JS/AnimateTransition#1]
I really like the snappiness in your animations and I think I will use this for a project that I am working on. To get it to work with Browserify, I have to shim it. It would be easier if you would publish it to npm.

From what I can tell, it's already ready for that. You'd just have to set this in your `package.json` (it's currently `"main": "animateTransition.js"`):

``` json
"main": "src/animateTransition"
```

**Comment by AntonTrofimenkoMobiDev** [comment]
We have changed the contents of the "package.json" and "bower.json". Now the main file is minified "src/animateTransition.min.js" and its source code "src/animateTransition.source.js". To view information about the library, use "bower info animate-transition" or "npm info animate-transition".
